
import { TestCaseListItem, TestCaseDetail } from '../types';

export const mockTestCases: TestCaseListItem[] = [
  {
    id: 'tc-001',
    name: 'Successful User Login',
    description: 'Verify that a registered user can log in successfully with valid credentials.',
    type: 'positive',
    priority: 'high',
    tags: ['auth', 'smoke'],
    aiGenerated: false,
    referencesCount: 2,
    referencedByCount: 1,
    ragReferencesCount: 0,
    manualReferencesCount: 2,
    derivedFromCount: 1,
    createdAt: '2023-10-26T10:00:00Z',
    updatedAt: '2023-10-26T11:30:00Z',
  },
  {
    id: 'tc-002',
    name: 'Failed Login with Invalid Password',
    description: 'Ensure that login fails and an appropriate error message is shown for an invalid password.',
    type: 'negative',
    priority: 'high',
    tags: ['auth', 'security'],
    aiGenerated: true,
    aiGenerationMethod: 'pure_ai',
    referencesCount: 1,
    referencedByCount: 2,
    ragReferencesCount: 0,
    manualReferencesCount: 1,
    derivedFromCount: 0,
    createdAt: '2023-10-25T14:20:00Z',
    updatedAt: '2023-10-25T14:20:00Z',
  },
  {
    id: 'tc-003',
    name: 'User Profile Update',
    description: 'A user should be able to update their profile information, like name and bio.',
    type: 'positive',
    priority: 'medium',
    tags: ['profile', 'user'],
    aiGenerated: true,
    aiGenerationMethod: 'rag',
    referencesCount: 1,
    referencedByCount: 3,
    ragReferencesCount: 1,
    manualReferencesCount: 0,
    derivedFromCount: 2,
    createdAt: '2023-10-24T09:00:00Z',
    updatedAt: '2023-10-24T09:45:00Z',
  },
  {
    id: 'tc-004',
    name: 'Add Item to Shopping Cart',
    description: 'Verify that a product can be successfully added to the shopping cart.',
    type: 'positive',
    priority: 'high',
    tags: ['ecommerce', 'cart'],
    aiGenerated: false,
    referencesCount: 0,
    referencedByCount: 1,
    ragReferencesCount: 0,
    manualReferencesCount: 0,
    derivedFromCount: 0,
    createdAt: '2023-10-23T16:00:00Z',
    updatedAt: '2023-10-23T16:00:00Z',
  },
];

export const mockTestCaseDetails: TestCaseDetail[] = [
  {
    id: 'tc-001',
    name: 'Successful User Login',
    description: 'Verify that a registered user can log in successfully with valid credentials.',
    type: 'positive',
    priority: 'high',
    steps: [
      { step: 'Navigate to the login page.', expectedResult: 'Login form is displayed with email and password fields.' },
      { step: 'Enter valid registered email.', expectedResult: 'Email is entered correctly.' },
      { step: 'Enter valid password.', expectedResult: 'Password is entered correctly.' },
      { step: 'Click the "Login" button.', expectedResult: 'User is redirected to the dashboard page.' },
    ],
    expectedResult: 'The user is successfully logged in and their session is active.',
    tags: ['auth', 'smoke'],
    aiGenerated: false,
    createdAt: '2023-10-26T10:00:00Z',
    updatedAt: '2023-10-26T11:30:00Z',
    references: [
      { id: 'ref-01', targetId: 'tc-002', referenceType: 'manual', target: { id: 'tc-002', name: 'Failed Login with Invalid Password', type: 'negative', priority: 'high' } },
      { id: 'ref-02', targetId: 'tc-004', referenceType: 'manual', target: { id: 'tc-004', name: 'Add Item to Shopping Cart', type: 'positive', priority: 'high' } },
    ],
    referencedBy: [
      { id: 'ref-03', sourceId: 'tc-003', referenceType: 'rag_retrieval', similarityScore: 0.82, source: { id: 'tc-003', name: 'User Profile Update', type: 'positive', priority: 'medium' } },
    ],
  },
  {
    id: 'tc-002',
    name: 'Failed Login with Invalid Password',
    description: 'Ensure that login fails and an appropriate error message is shown for an invalid password.',
    type: 'negative',
    priority: 'high',
    steps: [
      { step: 'Navigate to the login page.', expectedResult: 'Login form is displayed.' },
      { step: 'Enter valid registered email.', expectedResult: 'Email is entered.' },
      { step: 'Enter an invalid password.', expectedResult: 'Password is entered.' },
      { step: 'Click "Login".', expectedResult: 'An error message "Invalid credentials" is shown.' },
    ],
    expectedResult: 'User remains on the login page and is not authenticated.',
    tags: ['auth', 'security'],
    aiGenerated: true,
    aiGenerationMethod: 'pure_ai',
    originalPrompt: 'Create a negative test case for user login failure.',
    aiConfidence: 0.95,
    aiSuggestions: 'Consider testing for case-sensitivity in passwords.',
    createdAt: '2023-10-25T14:20:00Z',
    updatedAt: '2023-10-25T14:20:00Z',
    references: [
      { id: 'ref-04', targetId: 'tc-001', referenceType: 'manual', target: { id: 'tc-001', name: 'Successful User Login', type: 'positive', priority: 'high' } },
    ],
    referencedBy: [
      { id: 'ref-05', sourceId: 'tc-001', referenceType: 'manual', source: { id: 'tc-001', name: 'Successful User Login', type: 'positive', priority: 'high' } },
      { id: 'ref-06', sourceId: 'tc-003', referenceType: 'semantic_search', source: { id: 'tc-003', name: 'User Profile Update', type: 'positive', priority: 'medium' } },
    ],
  },
  {
    id: 'tc-003',
    name: 'User Profile Update',
    description: 'A user should be able to update their profile information, like name and bio.',
    type: 'positive',
    priority: 'medium',
    steps: [
      { step: 'Log in as a registered user.', expectedResult: 'User is on the dashboard.' },
      { step: 'Navigate to the profile page.', expectedResult: 'User profile details are shown.' },
      { step: 'Click "Edit Profile".', expectedResult: 'Profile fields become editable.' },
      { step: 'Change the user name and save.', expectedResult: 'A success message is shown and the name is updated.' },
    ],
    expectedResult: 'The user profile reflects the new information.',
    tags: ['profile', 'user'],
    aiGenerated: true,
    aiGenerationMethod: 'rag',
    originalPrompt: 'How to test user profile changes?',
    aiConfidence: 0.88,
    aiSuggestions: 'Also test character limits and special characters in fields.',
    createdAt: '2023-10-24T09:00:00Z',
    updatedAt: '2023-10-24T09:45:00Z',
    references: [
      { id: 'ref-03', targetId: 'tc-001', referenceType: 'rag_retrieval', similarityScore: 0.82, target: { id: 'tc-001', name: 'Successful User Login', type: 'positive', priority: 'high' } },
    ],
    referencedBy: [],
  },
  {
    id: 'tc-004',
    name: 'Add Item to Shopping Cart',
    description: 'Verify that a product can be successfully added to the shopping cart.',
    type: 'positive',
    priority: 'high',
    steps: [
      { step: 'Navigate to a product page.', expectedResult: 'Product details are visible.' },
      { step: 'Click "Add to Cart".', expectedResult: 'A confirmation message appears and cart icon updates.' },
      { step: 'Navigate to the cart page.', expectedResult: 'The added product is listed in the cart.' },
    ],
    expectedResult: 'The shopping cart contains the correct item with the correct quantity and price.',
    tags: ['ecommerce', 'cart'],
    aiGenerated: false,
    createdAt: '2023-10-23T16:00:00Z',
    updatedAt: '2023-10-23T16:00:00Z',
    references: [],
    referencedBy: [
      { id: 'ref-02', sourceId: 'tc-001', referenceType: 'manual', source: { id: 'tc-001', name: 'Successful User Login', type: 'positive', priority: 'high' } },
    ],
  },
];
