apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: testcase-management

resources:
  - ../../

namePrefix: dev-

commonLabels:
  environment: development

# Development-specific patches
patchesStrategicMerge:
  - replica-patch.yaml
  - resource-patch.yaml

# Development configuration
configMapGenerator:
  - name: dev-config
    literals:
      - NODE_ENV=development
      - LOG_LEVEL=debug

replicas:
  - name: backend
    count: 1
  - name: frontend  
    count: 1
  - name: ai-service
    count: 1